
service_agent_conf_path: "/tmp"
main_proccess:
 mongo:
  host: 172.17.100.169
  port: 28015
  database: YandexData
 rabbit:
  host: 172.17.100.169:5672
  username: test
  password: test
  queue:  testtesttest
 redis:
  url: redis://:@172.17.100.169:6379/0
  branch: TestTest
post_proccess:
 rabbit:
  host: 172.17.100.169:5672
  username: test
  password: test
  queue:  tempQuery
 yandex_task:
  mongo:
   host_url: mongodb://172.17.100.168:2375
   database: YandexData
   collection: Posts
